const now = new Date();

const daysAgo = (days, hours = 0, minutes = 0) => {
  const value = new Date(now);
  value.setDate(value.getDate() - days);
  value.setHours(hours, minutes, 0, 0);
  return value.toISOString();
};

export const MOCK_MANAGER_OPERATIONS_DASHBOARD = {
  businessDate: now.toISOString().slice(0, 10),
  generatedAt: now.toISOString(),
  autoRefreshEnabled: false,
  refreshIntervalSeconds: 300,
  todayTours: [
    {
      scheduleId: 101,
      adventureId: 12,
      adventureName: 'Ella Summit Trail',
      startDateTime: daysAgo(0, 7, 30),
      endDateTime: daysAgo(0, 11, 0),
      status: 'Upcoming',
      assignedGuideName: 'Nimali Perera',
      guideAssigned: true,
      guideAssignmentRequired: false,
      quickActionLabel: 'Guide confirmed',
      checkedInCustomerCount: 8,
      availableSlots: 4,
      totalCapacity: 12,
    },
    {
      scheduleId: 102,
      adventureId: 18,
      adventureName: 'Ravana Zipline Experience',
      startDateTime: daysAgo(0, 8, 15),
      endDateTime: daysAgo(0, 10, 45),
      status: 'In Progress',
      assignedGuideName: 'Kavindu Silva',
      guideAssigned: true,
      guideAssignmentRequired: false,
      quickActionLabel: 'Live on tour',
      checkedInCustomerCount: 11,
      availableSlots: 1,
      totalCapacity: 12,
    },
    {
      scheduleId: 103,
      adventureId: 9,
      adventureName: 'Misty Falls Hike',
      startDateTime: daysAgo(0, 9, 0),
      endDateTime: daysAgo(0, 12, 15),
      status: 'Upcoming',
      assignedGuideName: null,
      guideAssigned: false,
      guideAssignmentRequired: true,
      quickActionLabel: 'Needs guide assignment',
      checkedInCustomerCount: 6,
      availableSlots: 6,
      totalCapacity: 12,
    },
    {
      scheduleId: 104,
      adventureId: 22,
      adventureName: 'Ceylon Tea Estate Walk',
      startDateTime: daysAgo(0, 10, 0),
      endDateTime: daysAgo(0, 13, 0),
      status: 'Upcoming',
      assignedGuideName: 'Sandun Jayasinghe',
      guideAssigned: true,
      guideAssignmentRequired: false,
      quickActionLabel: 'Ready for departure',
      checkedInCustomerCount: 4,
      availableSlots: 8,
      totalCapacity: 12,
    },
    {
      scheduleId: 105,
      adventureId: 27,
      adventureName: 'Sunset Ridge Safari',
      startDateTime: daysAgo(0, 11, 30),
      endDateTime: daysAgo(0, 15, 0),
      status: 'Cancelled',
      assignedGuideName: null,
      guideAssigned: false,
      guideAssignmentRequired: true,
      quickActionLabel: 'Replacement guide needed',
      checkedInCustomerCount: 0,
      availableSlots: 14,
      totalCapacity: 14,
    },
    {
      scheduleId: 106,
      adventureId: 30,
      adventureName: 'Waterfall Discovery Loop',
      startDateTime: daysAgo(0, 13, 0),
      endDateTime: daysAgo(0, 16, 15),
      status: 'Completed',
      assignedGuideName: 'Pasindu Nadeesh',
      guideAssigned: true,
      guideAssignmentRequired: false,
      quickActionLabel: 'Completed successfully',
      checkedInCustomerCount: 12,
      availableSlots: 0,
      totalCapacity: 12,
    },
    {
      scheduleId: 107,
      adventureId: 33,
      adventureName: 'Forest Canopy Ride',
      startDateTime: daysAgo(0, 14, 30),
      endDateTime: daysAgo(0, 17, 45),
      status: 'In Progress',
      assignedGuideName: 'Amali Rodrigo',
      guideAssigned: true,
      guideAssignmentRequired: false,
      quickActionLabel: 'Midway through route',
      checkedInCustomerCount: 9,
      availableSlots: 3,
      totalCapacity: 12,
    },
  ],
  issues: [
    {
      alertId: 7001,
      scheduleId: 103,
      type: 'guide',
      priority: 'HIGH',
      title: 'Guide assignment missing',
      message: 'Tour is still waiting for a confirmed guide.',
      raisedAt: daysAgo(0, 6, 25),
    },
    {
      alertId: 7002,
      scheduleId: 105,
      type: 'capacity',
      priority: 'MEDIUM',
      title: 'Capacity change request',
      message: 'Guest list is pending a reschedule after cancellation.',
      raisedAt: daysAgo(0, 5, 55),
    },
    {
      alertId: 7003,
      scheduleId: 107,
      type: 'checkin',
      priority: 'LOW',
      title: 'Late check-in watch',
      message: 'Two guests checked in after the opening window.',
      raisedAt: daysAgo(0, 4, 40),
    },
  ],
  weeklyOccupancy: [
    { date: daysAgo(6, 0, 0), dayLabel: 'Mon', bookedCapacity: 32, availableCapacity: 14, totalCapacity: 46 },
    { date: daysAgo(5, 0, 0), dayLabel: 'Tue', bookedCapacity: 35, availableCapacity: 11, totalCapacity: 46 },
    { date: daysAgo(4, 0, 0), dayLabel: 'Wed', bookedCapacity: 38, availableCapacity: 8, totalCapacity: 46 },
    { date: daysAgo(3, 0, 0), dayLabel: 'Thu', bookedCapacity: 41, availableCapacity: 5, totalCapacity: 46 },
    { date: daysAgo(2, 0, 0), dayLabel: 'Fri', bookedCapacity: 39, availableCapacity: 7, totalCapacity: 46 },
    { date: daysAgo(1, 0, 0), dayLabel: 'Sat', bookedCapacity: 43, availableCapacity: 3, totalCapacity: 46 },
    { date: daysAgo(0, 0, 0), dayLabel: 'Sun', bookedCapacity: 44, availableCapacity: 2, totalCapacity: 46 },
  ],
};

export const MOCK_SHIFT_OVERVIEW = {
  generatedAt: now.toISOString(),
  autoRefreshEnabled: false,
  refreshIntervalSeconds: 300,
  ownerMetrics: {
    businessDate: now.toISOString().slice(0, 10),
    totalLaborHours: 118,
    estimatedShiftCost: 245000,
  },
  departments: [
    {
      departmentCode: 'ROOM_SERVICE',
      departmentName: 'Room Service',
      understaffed: false,
      warning: null,
      onShiftStaff: [
        { shiftId: 401, staffId: 'rs-01', staffName: 'Naveen Fernando', shiftStartAt: daysAgo(0, 6, 0), currentTaskAssignment: 'Serving Room 203', lastActivityAt: daysAgo(0, 6, 28) },
        { shiftId: 401, staffId: 'rs-02', staffName: 'Dineth Perera', shiftStartAt: daysAgo(0, 6, 30), currentTaskAssignment: 'New order queue', lastActivityAt: daysAgo(0, 6, 10) },
      ],
    },
    {
      departmentCode: 'HOUSEKEEPING',
      departmentName: 'Housekeeping',
      understaffed: true,
      warning: 'Two rooms are pending cleanup',
      onShiftStaff: [
        { shiftId: 402, staffId: 'hk-01', staffName: 'Tharushi Silva', shiftStartAt: daysAgo(0, 5, 30), currentTaskAssignment: 'Villa wing', lastActivityAt: daysAgo(0, 5, 55) },
        { shiftId: 402, staffId: 'hk-02', staffName: 'Kasun Jayawardena', shiftStartAt: daysAgo(0, 6, 10), currentTaskAssignment: 'Lobby suites', lastActivityAt: daysAgo(0, 5, 50) },
      ],
    },
    {
      departmentCode: 'LAUNDRY',
      departmentName: 'Laundry',
      understaffed: false,
      warning: null,
      onShiftStaff: [
        { shiftId: 403, staffId: 'ld-01', staffName: 'Isuru Bandara', shiftStartAt: daysAgo(0, 7, 0), currentTaskAssignment: 'Linen processing', lastActivityAt: daysAgo(0, 6, 44) },
      ],
    },
  ],
};

export const MOCK_ROOM_SERVICE_DASHBOARD = {
  generatedAt: now.toISOString(),
  autoRefreshEnabled: false,
  staleThresholdMinutes: 30,
  activeOrders: [
    { orderId: 9001, roomNumber: 203, floorNumber: 2, itemsOrdered: ['Club Sandwich', 'Iced Tea'], placedAt: daysAgo(0, 6, 55), assignedStaffId: 'rs-01', assignedStaffName: 'Naveen Fernando', status: 'RECEIVED', staleFlag: false, lastStatusUpdatedAt: daysAgo(0, 6, 40) },
    { orderId: 9002, roomNumber: 118, floorNumber: 1, itemsOrdered: ['Chicken Curry', 'Rice'], placedAt: daysAgo(0, 6, 25), assignedStaffId: 'rs-02', assignedStaffName: 'Dineth Perera', status: 'PREPARING', staleFlag: false, lastStatusUpdatedAt: daysAgo(0, 6, 12) },
    { orderId: 9003, roomNumber: 412, floorNumber: 4, itemsOrdered: ['Pasta Alfredo'], placedAt: daysAgo(0, 5, 50), assignedStaffId: null, assignedStaffName: null, status: 'RECEIVED', staleFlag: false, lastStatusUpdatedAt: daysAgo(0, 5, 42) },
    { orderId: 9004, roomNumber: 305, floorNumber: 3, itemsOrdered: ['Fruit Platter', 'Sparkling Water'], placedAt: daysAgo(0, 5, 20), assignedStaffId: 'rs-03', assignedStaffName: 'Chathura Wijesinghe', status: 'DELIVERED', staleFlag: false, lastStatusUpdatedAt: daysAgo(0, 4, 58) },
    { orderId: 9005, roomNumber: 219, floorNumber: 2, itemsOrdered: ['Hot Chocolate'], placedAt: daysAgo(0, 4, 40), assignedStaffId: 'rs-04', assignedStaffName: 'Malsha Dissanayake', status: 'PREPARING', staleFlag: true, lastStatusUpdatedAt: daysAgo(0, 4, 5) },
  ],
};

export const MOCK_ROOM_SERVICE_DAILY_SUMMARY = {
  businessDate: now.toISOString().slice(0, 10),
  totalOrders: 22,
  averageDeliveryMinutes: 18,
  unresolvedOrdersCount: 4,
  unresolvedOrders: [
    MOCK_ROOM_SERVICE_DASHBOARD.activeOrders[0],
    MOCK_ROOM_SERVICE_DASHBOARD.activeOrders[1],
    MOCK_ROOM_SERVICE_DASHBOARD.activeOrders[2],
    MOCK_ROOM_SERVICE_DASHBOARD.activeOrders[4],
  ],
};

export const MOCK_MANAGER_ROOM_PURCHASES = [
  {
    id: 'purchase-1',
    transactionId: 'TXN-45012',
    bookingReferenceId: 'BR-10081',
    bookingId: 10081,
    guestName: 'Anjali Wickramasinghe',
    guestEmail: 'anjali@example.com',
    roomName: 'Deluxe Suite',
    roomNumber: 203,
    amount: 42000,
    currency: 'LKR',
    status: 'SUCCESS',
    purchasedAt: daysAgo(0, 6, 50),
  },
  {
    id: 'purchase-2',
    transactionId: 'TXN-45013',
    bookingReferenceId: 'BR-10082',
    bookingId: 10082,
    guestName: 'Mihiri Perera',
    guestEmail: 'mihiri@example.com',
    roomName: 'Mountain View King',
    roomNumber: 118,
    amount: 51500,
    currency: 'LKR',
    status: 'PENDING',
    purchasedAt: daysAgo(0, 6, 15),
  },
  {
    id: 'purchase-3',
    transactionId: 'TXN-45014',
    bookingReferenceId: 'BR-10077',
    bookingId: 10077,
    guestName: 'Kavindi Herath',
    guestEmail: 'kavindi@example.com',
    roomName: 'Family Chalet',
    roomNumber: 412,
    amount: 78300,
    currency: 'LKR',
    status: 'SUCCESS',
    purchasedAt: daysAgo(0, 5, 58),
  },
  {
    id: 'purchase-4',
    transactionId: 'TXN-45015',
    bookingReferenceId: 'BR-10084',
    bookingId: 10084,
    guestName: 'Ravindu Jayasuriya',
    guestEmail: 'ravindu@example.com',
    roomName: 'Garden Villa',
    roomNumber: 305,
    amount: 60250,
    currency: 'LKR',
    status: 'REFUNDED',
    purchasedAt: daysAgo(0, 5, 14),
  },
  {
    id: 'purchase-5',
    transactionId: 'TXN-45016',
    bookingReferenceId: 'BR-10088',
    bookingId: 10088,
    guestName: 'Sanduni De Silva',
    guestEmail: 'sanduni@example.com',
    roomName: 'Signature Loft',
    roomNumber: 219,
    amount: 88800,
    currency: 'LKR',
    status: 'SUCCESS',
    purchasedAt: daysAgo(0, 4, 30),
  },
  {
    id: 'purchase-6',
    transactionId: 'TXN-45017',
    bookingReferenceId: 'BR-10091',
    bookingId: 10091,
    guestName: 'Pasindu Fernando',
    guestEmail: 'pasindu@example.com',
    roomName: 'Presidential Suite',
    roomNumber: 501,
    amount: 145000,
    currency: 'LKR',
    status: 'SUCCESS',
    purchasedAt: daysAgo(0, 3, 55),
  },
  {
    id: 'purchase-7',
    transactionId: 'TXN-45018',
    bookingReferenceId: 'BR-10094',
    bookingId: 10094,
    guestName: 'Himali Wickramarathne',
    guestEmail: 'himali@example.com',
    roomName: 'Lake View Double',
    roomNumber: 410,
    amount: 46800,
    currency: 'LKR',
    status: 'PENDING',
    purchasedAt: daysAgo(0, 3, 20),
  },
  {
    id: 'purchase-8',
    transactionId: 'TXN-45019',
    bookingReferenceId: 'BR-10096',
    bookingId: 10096,
    guestName: 'Dulanga Malitha',
    guestEmail: 'dulanga@example.com',
    roomName: 'Forest Cabin',
    roomNumber: 612,
    amount: 37900,
    currency: 'LKR',
    status: 'SUCCESS',
    purchasedAt: daysAgo(0, 2, 45),
  },
];
